/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-02 03:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_005fexam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table, th, td {\r\n");
      out.write("		border: 1px solid red;\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		//	text \r\n");
      out.write("		$(\"#btn1\").click(function() {\r\n");
      out.write("			//alert(\"눌렀네\");\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test01.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"text\" ,			//	가져오는 결과 타입\r\n");
      out.write("				//data : 		,			//	서버에 보낼때 같이 가는 데이터 (파라미터)\r\n");
      out.write("				//async : true 또는 false	 ,	//	비동기(기본, 생략, true) , 동기(false)\r\n");
      out.write("				success : function (data) {\r\n");
      out.write("					$(\"#result\").append(data);		//	성공하면 result 에 담자\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		$(\"#btn2\").click(function() {\r\n");
      out.write("			//alert(\"btn2\");\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test02.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"xml\" ,			//	가져오는 결과 타입\r\n");
      out.write("				//data : 		,			//	서버에 보낼때 같이 가는 데이터 (파라미터)\r\n");
      out.write("				//async : true 또는 false	 ,	//	비동기(기본, 생략, true) , 동기(false)\r\n");
      out.write("				success : function (data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr><th>종류</th><th>가격</th></tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					//	데이터가 여러개이므로 find 로 태그를 찾는다.\r\n");
      out.write("					$(data).find(\"product\").each(function() {\r\n");
      out.write("						let name = $(this).find(\"name\").text();\r\n");
      out.write("						let price = $(this).find(\"price\").text();\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + name + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + price + \"</td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		//	다른방법\r\n");
      out.write("		$(\"#btn3\").on(\"click\", function() {\r\n");
      out.write("			//alert(\"btn3\");\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test03.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"xml\" ,			//	가져오는 결과 타입\r\n");
      out.write("				//data : 		,			//	서버에 보낼때 같이 가는 데이터 (파라미터)\r\n");
      out.write("				//async : true 또는 false	 ,	//	비동기(기본, 생략, true) , 동기(false)\r\n");
      out.write("				success : function (data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr><th>차량 종류</th><th>차량 개수</th></tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					$(data).find(\"product\").each(function() {\r\n");
      out.write("						//	attr 로 속성을 찾자\r\n");
      out.write("						let name = $(this).attr(\"name\");\r\n");
      out.write("						let count = $(this).attr(\"count\");\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + name + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + count + \"</td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);		//	성공하면 result 에 담자\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		$(\"#btn4\").on(\"click\", function() {\r\n");
      out.write("			//alert(\"btn4\");\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test04.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"xml\" ,			//	가져오는 결과 타입\r\n");
      out.write("				//data : 		,			//	서버에 보낼때 같이 가는 데이터 (파라미터)\r\n");
      out.write("				//async : true 또는 false	 ,	//	비동기(기본, 생략, true) , 동기(false)\r\n");
      out.write("				success : function (data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr><th>회사</th><th>차량 종류</th><th>차량 개수</th></tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					$(data).find(\"product\").each(function() {\r\n");
      out.write("						let company = $(this).text();\r\n");
      out.write("						let name = $(this).attr(\"name\");\r\n");
      out.write("						let count = $(this).attr(\"count\");\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + company + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + name + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + count + \"</td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);		//	성공하면 result 에 담자\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		$(\"#btn5\").on(\"click\", function() {\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test05.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"xml\" ,			//	가져오는 결과 타입\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr>\"\r\n");
      out.write("					table += \"<th colspan='4'>\"\r\n");
      out.write("					table += $(data).find(\"weather\").attr(\"year\") + \"년 \";\r\n");
      out.write("					table += $(data).find(\"weather\").attr(\"month\") + \"월 \";\r\n");
      out.write("					table += $(data).find(\"weather\").attr(\"day\") + \"일 \";\r\n");
      out.write("					table += $(data).find(\"weather\").attr(\"hour\") + \"시 \";\r\n");
      out.write("					table += \"</th></tr>\";\r\n");
      out.write("					table += \"<tr><th>지역</th><th>온도</th><th>상태</th><th>아이콘</th>\"\r\n");
      out.write("					table += \"</tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					$(data).find(\"local\").each(function() {\r\n");
      out.write("						let local = $(this).text();\r\n");
      out.write("						let ta = $(this).attr(\"ta\");\r\n");
      out.write("						let desc = $(this).attr(\"desc\");\r\n");
      out.write("						let icon = $(this).attr(\"icon\");\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + local + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + ta + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + desc + \"</td>\";\r\n");
      out.write("						table += \"<td><img src = 'http://www.kma.go.kr/images/icon/NW/NB\" \r\n");
      out.write("									+ icon + \".png'></td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		$(\"#btn6\").on(\"click\", function() {\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test06.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"json\" ,			//	가져오는 결과 타입\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr><th>이름</th><th>범위</th></tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					//	key 가 인덱스고, value 가 객체이다.\r\n");
      out.write("					$.each(data, function(index, object) {\r\n");
      out.write("						//console.log(\"key\", index);\r\n");
      out.write("						//console.log(\"value\", object);\r\n");
      out.write("						let name = object.name;\r\n");
      out.write("						let scope = object.scope;\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + name + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + scope + \"</td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});	\r\n");
      out.write("//==================================================================================\r\n");
      out.write("		$(\"#btn7\").on(\"click\", function() {\r\n");
      out.write("			$(\"#result\").empty();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"test07.do\" ,			// 	서버주소\r\n");
      out.write("				method : \"post\" ,			//	전달방식\r\n");
      out.write("				dataType : \"json\" ,			//	가져오는 결과 타입\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					let table = \"<table>\";\r\n");
      out.write("					table += \"<thead><tr>\";\r\n");
      out.write("					table += \"<th>시·도별(1)</th>\";\r\n");
      out.write("					table += \"<th>총인구 (명)</th>\";\r\n");
      out.write("					table += \"<th>1차 접종 누계</th>\";\r\n");
      out.write("					table += \"<th>2차 접종 누계</th>\";\r\n");
      out.write("					table += \"<th>1차 접종 퍼센트</th>\";\r\n");
      out.write("					table += \"<th>2차 접종 퍼센트</th>\";\r\n");
      out.write("					table += \"</tr></thead>\";\r\n");
      out.write("					table += \"<tbody>\";\r\n");
      out.write("					\r\n");
      out.write("					$.each(data, function(index, obj) {\r\n");
      out.write("						//	자바스크립트에서 천단위 코마(내장함수)\r\n");
      out.write("						// 	천단위 콤마(내장함수) : toLocaleString()\r\n");
      out.write("						//	소수점 2자리까지 \r\n");
      out.write("						//	: toLocaleString('ko-KR', {maximumFractionDigits:2})\r\n");
      out.write("						table += \"<tr>\";\r\n");
      out.write("						table += \"<td>\" + obj['시·도별(1)'] + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + obj['총인구 (명)'].toLocaleString() + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + obj['1차 접종 누계'].toLocaleString() + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + obj['2차 접종 누계'].toLocaleString() + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + obj['1차 접종 퍼센트'].toLocaleString('ko-KR', {maximumFractionDigits:2}) + \"</td>\";\r\n");
      out.write("						table += \"<td>\" + obj['2차 접종 퍼센트'].toLocaleString('ko-KR', {maximumFractionDigits:2}) + \"</td>\";\r\n");
      out.write("						table += \"</tr>\";\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					table += \"</tbody>\";\r\n");
      out.write("					table += \"</table>\";\r\n");
      out.write("					$(\"#result\").append(table);\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"읽기 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});	\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<h2>Ajax 연습하는 장소</h2>\r\n");
      out.write("	\r\n");
      out.write("	<button id=\"btn1\">text</button>\r\n");
      out.write("	<button id=\"btn2\">xml_01</button>\r\n");
      out.write("	<button id=\"btn3\">xml_02</button>\r\n");
      out.write("	<button id=\"btn4\">xml_03</button>\r\n");
      out.write("	<button id=\"btn5\">날씨_xml</button>\r\n");
      out.write("	<button id=\"btn6\">json_01</button>\r\n");
      out.write("	<button id=\"btn7\">json_02</button>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div id=\"result\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
